spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: oauth-server
  profiles:
    active: local
#  cloud:
#    stream:
#      rocketmq:
#        binder:
#          name-server: 182.151.18.126:9876
#          enable-msg-trace: false
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
server:
  port: 8012
  tomcat:
    #最大连接等待数,默认100
    accept-count: 1000
    #最小工作线程数,默认10
    min-spare-threads: 100
    #最大工作线程数,默认200
    max-threads: 1000
    #请求体最大大小,默认2MB
    max-swallow-size: -1
  servlet:
    session:
      cookie:
        name: OAUTH2SESSION
dist:
  lock:
    api: enabled
mybatis-plus:
  auto-fill:
    enabled: true
  global-config:
    banner: false
##feign参数优化
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000
        loggerLevel: full  ## 配合logging.level=trace debug用于开发调式日志
  compression:
    request:
      enabled: true
      mine-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: true
  hystrix:
    enabled: false
logging:
  level:
    org.springframework: INFO
cnasoft:
  security:
    ignore:
      httpUrls: >
        /oauth/user/token
    code:
      # 忽略验证码的应用编号
      ignoreClientCode: none
  oauth2:
    token:
      store:
        #type: authJwt
        type: redis
  #多租户配置
  tenant:
    enable: false
    ignoreTables:
      - oauth_client_details
encrypt:
  key-store:
    location: classpath:hm.jks
    secret: hm@123
    alias: hm
management:
  server:
    port: 8022
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management
  endpoint:
    health:
      show-details: always
swagger:
  enable: true
  title: 认证中心
  description: 提供注册、登录、OAuth2.0授权等
  version: 1.0.0
  base-package: com.cnasoft.health.auth.controller
  group-name: 认证中心
captcha:
  slider:
    # 如果项目中使用到了redis,滑块验证码会自动把验证码数据存到redis中,这里配置redis的key的前缀,默认是captcha:slider
    prefix: |-
      captcha:slider
    # 验证码过期时间,默认是1分钟,单位毫秒,可以根据自身业务进行调整
    expire: 20000
    # 使用加载系统自带的资源,默认是true
    init-default-resource: true
    # 验证码会提前缓存一些生成好的验证数据,默认是20
    cacheSize: 20
    # 因为缓存池会缓存 webp 和jpg+png 两种类型的图片,所有这里可以配置webp生成的数量,默认是 总缓存的70%(captcha.cacheSize*0.7)
    webp-cache-size: 16
    # 缓存拉取失败后等待时间 默认是 5秒钟
    wait-time: 5000
    # 缓存检查间隔 默认是2秒钟
    period: 2000
    # 是否加入混淆滑块，默认不加入
    obfuscate: false

task-executor:
  corePoolSize: 5
  maxPoolSize: 200
  queueCapacity: 1000
  threadNamePrefix: OauthServerTaskExecutor-